services:
  redis:
    image: "redis:7.2"
    expose:
      - 6379
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 5s
      timeout: 20s
      retries: 5
    restart: unless-stopped

  bot:
    build: .
    environment:
      PYTHONPATH: ".:./src"
    command: poetry run exchange_bot
    env_file:
      - .env
    depends_on:
      - redis
    restart: always

  worker:
    build: .
    environment:
      PYTHONPATH: ".:./src"
    command: poetry run faststream run --factory exchange_rate_bot.main.queue:create_app
    env_file:
      - .env
    depends_on:
      - redis
    restart: always

volumes:
  redis_data: